#Thank you for choosing LuckyBounties, here's some information regarding the config:
#     The time setting, 'ranking-message-interval' is using the default tps of 20 ticks to operate
#     So if your Server runs on a higher tick rate, the interval will actually be shorter.

#==MESSAGES
#GLOBAL    When these are false, the plugin will default to local messages (Just the player performing the action)
bounty-set-global: true                     #Sends a notification for everyone to see when a bounty is set              (LANG: bounty-set-global)
bounty-take-global: true                    #Sends a notification for everyone when a player with bounties is killed    (LANG: bounty-take-global)
bounty-take-eco: false                      #Toggles the death-message to eco mode (LANG: eco-bounty-take)
take-message-overrides-death-message: true  #When false, instead of overriding minecrafts death message it will send a normal server message

#==INTEGRATIONS
papi-integration: false                     #Activates the PlaceholderAPI integration, so you can use placeholders

#ECONOMY
vault-integration: false                    #Activates the Vault integration so you can use an economy
default-amount: 100                         #The default amount of currency that gets set in the bounty menu
eco-item: gold_nugget                       #The item used to represent your currency
minimum-amount: 0                           #The minimum amount for bounties, bounties below this amount are not allowed

#==ETXRAS
#RANKING SYSTEM             (LANG: Ranking message)
send-ranking-message: true                  #Every {ranking_message_interval} h/m/s a public notification, announcing the player with the most bounties will be sent
ranking-message-eco: false                  #Toggles the ranking message system from Item bounties to Eco bounties
ranking-message-interval: "1_h:1_m:1_s"     # 1m = 1 minute, 1h = 1 hour, 1s = 1 second

#SPECIAL SETTINGS
set-by-lore: false                          #Shows who set a bounty in the item-lore
disable-items: false                        #Disables the Item support of the plugin completely
allow-self-bounty: true                     #Allows players to set bounties on themselves
return-bounties-when-cleared: false         #Returns cleared bounties (feather-clicked, not individual-clicked) to setter

#TIMING STUFF
bounties-expire: false                      #Should bounties expire after a certain time ?
bounty-expire-time: "2_d:12_h:6_m:3_s"      #How long until bounties expire
return-after-expire: false                  #Should bounties be returned after they expire ?

cooldown-enabled: true                      #Enables a cooldown so your players cannot spam bounties
global-cooldown: false                      #If enabled, no one can set a bounty during that time, if disabled, the cooldown locks individual players instead of the entire server
cooldown-time: "10_s"                       #1m = 1 minute, 1h = 1 hour, 1s = 1 second

#LISTS
enable-blacklist: true
blacklist:
  - command_block                           #Blacklists Items from being set. (All these values will work: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
  - command_block_minecart

enable-whitelist: false
whitelist:                                  #Whitelist will overpower blacklist
  - diamond                                 #Will only allow these items as bounties. (All these values will work: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)

#OPERATOR SETTINGS
op-ignore-cooldown: false                   #Should Operators ignore the cooldown

#==DEBUG
debug-log: false                            #Only turn on when requested to search for a bug. Will log all the otherwise invisible backend plugin stuff